blog_categories = [
    "Technology",
    "Programming",
    "Data Science",
    "Machine Learning",
    "Web Development",
    "Mobile Development",
    "Design",
    "Business",
    "Finance",
    "Health & Wellness",
    "Education",
    "Lifestyle",
    "Travel",
    "Food",
    "Environment",
    "Personal Development",
    "Productivity",
    "Career Advice",
    "News",
    "Marketing",
    "Startups",
    "Science",
    "Sports",
    "Art & Culture",
    "Entertainment",
    "Gaming",
    "Politics",
    "Real Estate",
    "Finance",
    "Parenting",
    "Relationships",
]